---
title: "New functionalities for summarytools"
author: "antuki"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette: 
    css: 
    - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
vignette: >
  %\VignetteIndexEntry{Recommendations for Rmarkdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
library(knitr)
opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=TRUE, results='asis')
```
```{r, echo=FALSE}
library(summarytools)
st_css()

st_options(bootstrap.css     = FALSE,       # Already part of the theme so no need for it
           plain.ascii       = FALSE,       # One of the essential settings
           style             = "rmarkdown", # Idem.
           round.digits = 1, #nombre de chiffres après la virgule pour les pourcentages
           dfSummary.silent  = TRUE,   # Suppresses messages about temporary files
           dfSummary.varnumbers = FALSE,
           footnote          = NA,          # Keeping the results minimalistic
           subtitle.emphasis = FALSE)       # For the vignette theme, this gives
                                            # much better results. Your mileage may vary.

```


## Prepare data from questionr package

```{r eval=FALSE}
library(dplyr)
library(questionr)
data(hdv2003)
```

```{r include=FALSE}
library(dplyr)
library(questionr)
data(hdv2003)
```

## dfSummary from the initial summarytools package

```{r}
dfSummary(hdv2003 %>% select(age,sexe),column_weight =NULL)
```

## dfSummary with weights
(new option implemented)

```{r}
dfSummary(hdv2003 %>% select(age,sexe,poids),column_weight = "poids")
```


## Simple summary with weight
variable clso with weight ("poids" variable)

```{r}
dfSummary_simple(bdd=hdv2003,nom_var="clso",nom_croisement=NULL,column_weight="poids")
```

## With a filter 
filter : (freres.soeurs!=8")
```{r}
dfSummary_simple(bdd=hdv2003,nom_var="clso",nom_croisement=NULL,column_weight="poids",filtres="freres.soeurs!=8")
```

## With cross-tabulation 
cross-tabulation = (occup variable) => one line for each modality of the cross-tabulation
```{r}
dfSummary_simple(bdd=hdv2003,nom_var="clso",nom_croisement="occup",column_weight="poids",filtres="freres.soeurs!=8",header_perso=TRUE)
```

